kind: Namespace
apiVersion: v1
metadata:
  labels:
    app: app-6-4
    env: dev
  name: yochay2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-6-4-server-home-folder-dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: "/"
